### ISSUE TITLE
cmd/upspin: panic on Windows

### ISSUE THREAD

**Issue by fawick** [upspin/upspin#298]
Upspin: https://github.com/upspin/upspin/commit/13f927641e81a9fb5ef0cccbcde35f4b41a96c97

```
C:\Users\fabian> go env
go version go1.8 windows/amd64

C:\Users\fabian> %GOPATH%\bin\upspin
panic: crypto/x509: system root pool is not available on Windows

goroutine 1 [running]:
upspin.io/config.init.1()
        c:/Users/fabian/go/src/upspin.io/config/initconfig.go:51 +0x79
upspin.io/config.init()
        c:/Users/fabian/go/src/upspin.io/config/user.go:22 +0xd8
main.init()
        c:/Users/fabian/go/src/upspin.io/cmd/upspin/whichaccess.go:52 +0x67
```

I would expect to get to see the usage message, at least.

**Comment by fawick** [comment]
Blocked by https://github.com/golang/go/issues/16736

**Comment by fawick** [comment]
Addressed in https://upspin-review.googlesource.com/c/8140/
