### ISSUE TITLE
dir/server/tree: possible race in test or timeout not being detected

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#300]
Got this once, but it did not recur:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42033ef70, 0x66b83e, 0x18, 0x676d20, 0xc420157c01)
	/usr/lib/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc42033ef70)
	/usr/lib/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc42033ef70, 0xc420157d78)
	/usr/lib/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc420414120, 0x7971a0, 0x16, 0x16, 0x0)
	/usr/lib/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc42047bf20, 0x4)
	/usr/lib/go/src/testing/testing.go:822 +0xfc
upspin.io/dir/server/tree.TestMain(0xc420157f20)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/all_test.go:1010 +0x95
main.main()
	upspin.io/dir/server/tree/_test/_testmain.go:82 +0xf7

goroutine 71 [select]:
upspin.io/dir/server/tree.(*watcher).watch(0xc4203e9780, 0x148)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:301 +0x167
created by upspin.io/dir/server/tree.(*Tree).Watch
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:127 +0x9d6

goroutine 31 [chan receive]:
upspin.io/dir/server/tree.TestWatchNonExistingNode(0xc42009ca90)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch_test.go:301 +0x9e9
testing.tRunner(0xc42009ca90, 0x676d20)
	/usr/lib/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2ca

goroutine 74 [select]:
upspin.io/dir/server/tree.(*watcher).watch(0xc42024cec0, 0x209)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:301 +0x167
created by upspin.io/dir/server/tree.(*Tree).Watch
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:127 +0x9d6

goroutine 76 [select]:
upspin.io/dir/server/tree.(*watcher).watch(0xc4201b33c0, 0x25c)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:301 +0x167
upspin.io/dir/server/tree.(*watcher).sendCurrentAndWatch(0xc4201b33c0, 0xc4202b7810, 0xc4202b6230, 0x66c207, 0x19, 0x1b7)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:195 +0x2f6
created by upspin.io/dir/server/tree.(*Tree).Watch
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:118 +0x746

goroutine 32 [select]:
upspin.io/dir/server/tree.(*watcher).watch(0xc420391700, 0x74)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:301 +0x167
upspin.io/dir/server/tree.(*watcher).sendCurrentAndWatch(0xc420391700, 0xc420392b60, 0xc420392850, 0x66c207, 0x19, 0x0)
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:195 +0x2f6
created by upspin.io/dir/server/tree.(*Tree).Watch
	/usr/local/google/home/edpin/projects/src/upspin.io/dir/server/tree/watch.go:118 +0x746
```

`go test -race` did not yield any insights. Likely just a glitch, but tracking here for further investigation.

**Comment by adg** [comment]
I got this one just now:

```
=== RUN   TestIntegration/kind=server/packing=eeintegrity/WatchErrors
panic: runtime error: makeslice: len out of range

goroutine 217 [running]:
upspin.io/upspin.(*DirEntry).Unmarshal(0xc422227d88, 0xc422340039, 0x1f9a, 0x1f9a, 0xffb, 0x0, 0x0, 0xc42001f900, 0xc422227bb8)
	/Users/adg/src/upspin.io/upspin/code.go:250 +0xa8a
upspin.io/dir/server/tree.(*LogEntry).unmarshal(0xc422227d80, 0xc420344bc0, 0x1000, 0xc422019000)
	/Users/adg/src/upspin.io/dir/server/tree/log.go:522 +0x92c
upspin.io/dir/server/tree.(*Log).ReadAt(0xc4211d7680, 0x1, 0x309, 0x0, 0x0, 0x0, 0x309, 0x0, 0x0)
	/Users/adg/src/upspin.io/dir/server/tree/log.go:218 +0x3e9
upspin.io/dir/server/tree.(*watcher).sendEventFromLog(0xc420a987c0, 0x309, 0xc420a987c0, 0x16, 0x3)
	/Users/adg/src/upspin.io/dir/server/tree/watch.go:263 +0x9b
upspin.io/dir/server/tree.(*watcher).watch(0xc420a987c0, 0x309)
	/Users/adg/src/upspin.io/dir/server/tree/watch.go:293 +0x7a
created by upspin.io/dir/server/tree.(*Tree).Watch
	/Users/adg/src/upspin.io/dir/server/tree/watch.go:127 +0x8ce
exit status 2
FAIL	upspin.io/test	17.709s
```

This looks like memory corruption to me, but I haven't investigated at all.

**Comment by xiang90** [comment]
I can take a look at this when I have time. You can assign it to me if this is not something super urgent.

**Comment by xiang90** [comment]
OK. I guess I already know what happened. Fixing...
