### ISSUE TITLE
cmd/upspin: runtime error:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tiago4orion** [upspin/upspin#314]
What version of Upspin are you using?
master
What operating system and processor architecture are you using?
Linux/amd64
What did you do?
upspin signup -server=server.company.com my@email.com
What did you expect to see?
signup
What did you see instead?
```
Configuration file written to:
	/home/i4k/upspin/config

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x69652b]

goroutine 1 [running]:
upspin.io/subcmd.BoolFlag(0xc4203ca120, 0x8e4abf, 0x6, 0xc4203b64f0)
	/home/i4k/.gvm/pkgsets/go1.8/global/src/upspin.io/subcmd/flag.go:53 +0x5b
main.(*State).keygenCommand(0xc4203be120, 0xc4203ca120)
	/home/i4k/.gvm/pkgsets/go1.8/global/src/upspin.io/cmd/upspin/keygen.go:69 +0x240
main.(*State).signup(0xc4203be120, 0xc420010260, 0x2, 0x2)
	/home/i4k/.gvm/pkgsets/go1.8/global/src/upspin.io/cmd/upspin/signup.go:164 +0xd4d
main.main()
	/home/i4k/.gvm/pkgsets/go1.8/global/src/upspin.io/cmd/upspin/main.go:130 +0x254
ERROR: exit status 2
```

**Comment by edpin** [comment]
Sorry about that. It's a bug. I have a fix for it.

**Comment by lborguetti** [comment]
Thanks @adg

**Comment by adg** [comment]
@lborguetti actually it was @edpin that did that.
