### ISSUE TITLE
upspin: getBytes panics on some input

### ISSUE THREAD

**Issue by shurcooL** [upspin/upspin#403]
This is [`getBytes`](https://github.com/upspin/upspin/blob/76bcdc318f6f2bd73411501de6707d89af43b0c7/upspin/code.go#L319-L331) from latest commit:

```Go
// getBytes unmarshals the byte slice at b (varint count followed by bytes)
// and returns the slice followed by the remaining bytes.
// If there is insufficient data, both return values will be nil.
func getBytes(b []byte) (data, remaining []byte) {
	u, n := binary.Varint(b)
	if u < 0 {
		return nil, nil
	}
	if n == 0 || len(b) < n+int(u) {
		return nil, nil
	}
	return getNBytes(b[n:], int(u))
}
```

Its documentation does not say that `getBytes` panics on certain input, but it does. So my guess is that it's a bug (otherwise, a problem with its docs).

[`binary.Varint`](https://godoc.org/encoding/binary#Varint) docs say:

> Varint decodes an int64 from buf and returns that value and the number of bytes read (> 0). If an error occurred, the value is 0 and the number of bytes n is <= 0

A panic can happen because the code never checks if `n < 0`. So `n` can be a negative value, which causes `b[n:]` to panic with "slice bounds out of range".

Consider input `getBytes([]byte{0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x2})`:

```
binary.Varint(b) values: 0 -10
panic: runtime error: slice bounds out of range
```

Playground: https://play.golang.org/p/B7UgaNX0t7.

This is not theoretical, I saw this panic actually happen in upspin tests while looking into #389. /cc @adg It's pretty rare though, I only saw this once.

<details><summary>Output details from failed test run.</summary>

```
...
=== RUN   TestIntegration/kind=server/packing=eeintegrity/GlobLinkErrors
=== RUN   TestIntegration/kind=server/packing=eeintegrity/SequenceNumbers
=== RUN   TestIntegration/kind=server/packing=eeintegrity/RootDeletion
2017/06/27 04:58:07.331883 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.341433 Deleting root "test-friend@upspin.io/"
2017/06/27 04:58:07.350663 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.357500 Deleting root "test-friend@upspin.io/"
=== RUN   TestIntegration/kind=server/packing=eeintegrity/ReadAccess
=== RUN   TestIntegration/kind=server/packing=eeintegrity/GroupAccess
2017/06/27 04:58:07.847258 Created root: test-friend@upspin.io/
2017/06/27 04:58:07.968425 Deleting root "test-friend@upspin.io/"
2017/06/27 04:58:07.994841 dir/server.Delete: Error removing group file: access.RemoveGroup: item does not exist: group does not exist
=== RUN   TestIntegration/kind=server/packing=eeintegrity/WriteReadAllAccessFile
=== RUN   TestIntegration/kind=server/packing=eeintegrity/Watch
2017/06/27 04:58:08.922649 dir/server.Watch: timeout sending event for test@upspin.io
2017/06/27 04:58:08.924043 dir/server.Watch: timeout sending event for test@upspin.io
2017/06/27 04:58:08.924793 dir/server.Watch: timeout sending event for test@upspin.io
=== RUN   TestIntegration/kind=server/packing=eeintegrity/WatchErrors
panic: runtime error: slice bounds out of range

goroutine 800 [running]:
upspin.io/upspin.getBytes(0xc4223bfca0, 0x15, 0x15, 0x4, 0x15, 0xc4223bfc88, 0xc4223bfc90, 0x0, 0x0)
    /home/travis/gopath/src/upspin.io/upspin/code.go:330 +0x1c5
upspin.io/upspin.(*DirEntry).Unmarshal(0xc420e75cf8, 0xc4223bfca0, 0x15, 0x15, 0x15, 0x15, 0x0, 0x0, 0x4159b0)
    /home/travis/gopath/src/upspin.io/upspin/code.go:223 +0x6e
upspin.io/dir/server/tree.(*LogEntry).unmarshal(0xc420e75cf0, 0xc4223bfc80, 0xc4223bfc80, 0x309)
    /home/travis/gopath/src/upspin.io/dir/server/tree/log.go:877 +0xf96
upspin.io/dir/server/tree.(*Reader).ReadAt(0xc42266ab80, 0x309, 0x40f19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/upspin.io/dir/server/tree/log.go:407 +0x948
upspin.io/dir/server/tree.(*watcher).sendEventFromLog(0xc42266ad40, 0x309, 0xc42266ad40, 0xc421402160, 0xb24165)
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:284 +0x100
upspin.io/dir/server/tree.(*watcher).watch(0xc42266ad40, 0x309)
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:312 +0x8b
created by upspin.io/dir/server/tree.(*Tree).Watch
    /home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:146 +0x892
exit status 2
FAIL    upspin.io/test  128.482s


The command "go test -v -short -race -count=10 -run=TestIntegration/kind=server ./test" exited with 1.

Done. Your build exited with 1.
```

Source: https://travis-ci.org/shurcooL/upspin/builds/247372793.

</details>

**Comment by edpin** [comment]
We've added some protection to avoid negative values and very large values. However, sometimes we are in the wrong offset for the LogEntry but these checks pass and we hit negative or large values later on. We can add more protection though. 

I also commented on other related places that call this function on https://github.com/upspin/upspin/issues/347#issuecomment-289814750

**Comment by edpin** [comment]
https://upspin-review.googlesource.com/c/10400/
