### ISSUE TITLE
cmd/cacheserver: concurrency bug

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#421]
```
% cacheserver -cachesize 5000000000  -addr localhost:8888 -cachedir /tmp/upspincache/
fatal error: concurrent map iteration and map write

goroutine 481 [running]:
runtime.throw(0x1423094, 0x26)
	/Users/r/go/src/runtime/panic.go:596 +0x95 fp=0xc4200554e8 sp=0xc4200554c8
runtime.mapiternext(0xc420055648)
	/Users/r/go/src/runtime/hashmap.go:778 +0x6fd fp=0xc420055580 sp=0xc4200554e8
runtime.mapiterinit(0x139ee00, 0xc4207defc0, 0xc420055648)
	/Users/r/go/src/runtime/hashmap.go:768 +0x270 fp=0xc4200555e8 sp=0xc420055580
upspin.io/dir/dircache.appendChildren(0xc421196e10, 0x84, 0x90, 0xc4207defc0, 0x7e, 0xc421196e10, 0x84)
	/Users/r/src/upspin.io/dir/dircache/log.go:1257 +0x12d fp=0xc4200556b8 sp=0xc4200555e8
upspin.io/dir/dircache.(*clogEntry).marshal(0xc42128a600, 0x0, 0x0, 0x0, 0x58, 0xc42128a600)
	/Users/r/src/upspin.io/dir/dircache/log.go:1086 +0x21c fp=0xc420055758 sp=0xc4200556b8
upspin.io/dir/dircache.(*clog).appendToLogFile(0xc420028c00, 0xc42128a600, 0x0, 0x0)
	/Users/r/src/upspin.io/dir/dircache/log.go:996 +0x58 fp=0xc4200557e8 sp=0xc420055758
upspin.io/dir/dircache.(*clog).append(0xc420028c00, 0xc42128a600, 0xc422534d9f, 0x12)
	/Users/r/src/upspin.io/dir/dircache/log.go:706 +0x4d fp=0xc420055818 sp=0xc4200557e8
upspin.io/dir/dircache.(*clog).logGlobRequest(0xc420028c00, 0xc421b1ea80, 0x80, 0x0, 0x0, 0xc4224f3a10, 0x2, 0x2)
	/Users/r/src/upspin.io/dir/dircache/log.go:700 +0x3d9 fp=0xc420055988 sp=0xc420055818
upspin.io/dir/dircache.(*server).Glob(0xc42016c0c0, 0xc421b1ea80, 0x80, 0x1, 0x1, 0xc420d64fc0, 0x87, 0xc42071ac50)
	/Users/r/src/upspin.io/dir/dircache/server.go:105 +0x28f fp=0xc420055a68 sp=0xc420055988
upspin.io/rpc/dirserver.(*server).Glob(0xc42005ed00, 0x15e95a0, 0xc42017f3e0, 0xc4225a6e00, 0x83, 0x200, 0x83, 0x200, 0x0, 0xc42016c06c)
	/Users/r/src/upspin.io/rpc/dirserver/server.go:110 +0x1b0 fp=0xc420055b80 sp=0xc420055a68
upspin.io/rpc/dirserver.(*server).Glob-fm(0x15e95a0, 0xc42017f3e0, 0xc4225a6e00, 0x83, 0x200, 0x0, 0x0, 0x0, 0x9)
	/Users/r/src/upspin.io/rpc/dirserver/server.go:47 +0x63 fp=0xc420055be0 sp=0xc420055b80
upspin.io/rpc.(*serverImpl).ServeHTTP(0xc42005ed40, 0x15e7f20, 0xc4201ec0e0, 0xc42236a900)
	/Users/r/src/upspin.io/rpc/server.go:179 +0x3fa fp=0xc420055cd8 sp=0xc420055be0
net/http.(*ServeMux).ServeHTTP(0xc420428360, 0x15e7f20, 0xc4201ec0e0, 0xc42236a900)
	/Users/r/go/src/net/http/server.go:2245 +0x130 fp=0xc420055d18 sp=0xc420055cd8
net/http.serverHandler.ServeHTTP(0xc42007dee0, 0x15e7f20, 0xc4201ec0e0, 0xc42236a900)
	/Users/r/go/src/net/http/server.go:2595 +0xb4 fp=0xc420055d48 sp=0xc420055d18
net/http.(*conn).serve(0xc4204a6320, 0x15e91e0, 0xc42049f480)
	/Users/r/go/src/net/http/server.go:1797 +0x71d fp=0xc420055fc8 sp=0xc420055d48
runtime.goexit()
	/Users/r/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420055fd0 sp=0xc420055fc8
created by net/http.(*Server).Serve
	/Users/r/go/src/net/http/server.go:2696 +0x288

goroutine 1 [chan receive, 45 minutes]:
main.main()
	/Users/r/src/upspin.io/cmd/cacheserver/main.go:53 +0x385

goroutine 17 [syscall, 45 minutes, locked to thread]:
runtime.goexit()
	/Users/r/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 6 [chan receive]:
upspin.io/serverutil.(*RateCounter).loop(0xc420079f50)
	/Users/r/src/upspin.io/serverutil/ratecounter.go:73 +0x53
created by upspin.io/serverutil.newRateCounter
	/Users/r/src/upspin.io/serverutil/ratecounter.go:45 +0x28d

goroutine 7 [chan receive]:
upspin.io/serverutil.(*RateCounter).loop(0xc420079f80)
	/Users/r/src/upspin.io/serverutil/ratecounter.go:73 +0x53
created by upspin.io/serverutil.newRateCounter
	/Users/r/src/upspin.io/serverutil/ratecounter.go:45 +0x28d

goroutine 8 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).scheduler(0xc4200612c0)
	/Users/r/src/upspin.io/store/storecache/wbq.go:175 +0x23c
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:119 +0x36a

goroutine 9 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x0)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 10 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x1)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 11 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x2)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 12 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x3)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 13 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x4)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 14 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x5)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 15 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x6)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 16 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x7)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 18 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x8)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 19 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x9)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 20 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xa)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 21 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xb)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 22 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xc)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 23 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xd)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 24 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xe)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 25 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0xf)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 26 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x10)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 27 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x11)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 28 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x12)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 29 [select, 45 minutes]:
upspin.io/store/storecache.(*writebackQueue).writer(0xc4200612c0, 0x13)
	/Users/r/src/upspin.io/store/storecache/wbq.go:302 +0x115
created by upspin.io/store/storecache.newWritebackQueue
	/Users/r/src/upspin.io/store/storecache/wbq.go:123 +0x39a

goroutine 30 [select, 45 minutes]:
upspin.io/dir/dircache.(*clog).rotater(0xc420028c00)
	/Users/r/src/upspin.io/dir/dircache/log.go:366 +0xf8
created by upspin.io/dir/dircache.openLog
	/Users/r/src/upspin.io/dir/dircache/log.go:197 +0x47c

goroutine 32 [IO wait, 45 minutes]:
internal/poll.runtime_pollWait(0x1781f90, 0x72, 0xffffffffffffffff)
	/Users/r/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200a0598, 0x72, 0x0, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200a0598, 0xffffffffffffff00, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200a0580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_unix.go:333 +0x1d7
net.(*netFD).accept(0xc4200a0580, 0xc420041e80, 0x10022c7, 0xc4204a63a0)
	/Users/r/go/src/net/fd_unix.go:240 +0x42
net.(*TCPListener).accept(0xc42000e148, 0x12b3458, 0x1055d70, 0xc420041ec8)
	/Users/r/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e148, 0x1430590, 0xc4204a6320, 0x15e92a0, 0xc420428450)
	/Users/r/go/src/net/tcpsock.go:237 +0x49
net/http.(*Server).Serve(0xc42007dee0, 0x15e7d60, 0xc42000e148, 0x0, 0x0)
	/Users/r/go/src/net/http/server.go:2671 +0x1b2
main.serve.func1(0xc4203fb6e0, 0xc42007dee0, 0x15e7d60, 0xc42000e148)
	/Users/r/src/upspin.io/cmd/cacheserver/serve.go:69 +0x3f
created by main.serve
	/Users/r/src/upspin.io/cmd/cacheserver/serve.go:68 +0x478

goroutine 35 [select]:
upspin.io/dir/dircache.(*proxiedDir).watch(0xc420011650, 0x1430902, 0xc420340d87, 0x1d, 0x0, 0x0)
	/Users/r/src/upspin.io/dir/dircache/proxied.go:207 +0x2bb
upspin.io/dir/dircache.(*proxiedDir).watcher(0xc420011650, 0x2, 0xc420340d87, 0x1d)
	/Users/r/src/upspin.io/dir/dircache/proxied.go:162 +0x1d1
created by upspin.io/dir/dircache.(*proxiedDirs).proxyFor
	/Users/r/src/upspin.io/dir/dircache/proxied.go:109 +0x33f

goroutine 50 [select]:
upspin.io/dir/remote.(*remote).Watch.func1(0xc4204560c0, 0xc420456060, 0xc420450040, 0xc420456000)
	/Users/r/src/upspin.io/dir/remote/remote.go:124 +0x14c
created by upspin.io/dir/remote.(*remote).Watch
	/Users/r/src/upspin.io/dir/remote/remote.go:121 +0x228

goroutine 68 [select, 45 minutes]:
net/http.(*persistConn).readLoop(0xc4204b6000)
	/Users/r/go/src/net/http/transport.go:1646 +0x7a7
created by net/http.(*Transport).dialConn
	/Users/r/go/src/net/http/transport.go:1168 +0xa2e

goroutine 70 [select]:
upspin.io/rpc.readFull(0x15e3420, 0xc42049e400, 0xc42009ed0c, 0x4, 0x4, 0xc420456000, 0x0, 0x0, 0x0)
	/Users/r/src/upspin.io/rpc/client.go:352 +0x16b
upspin.io/rpc.decodeStream(0x15e8de0, 0xc420456060, 0x15e63a0, 0xc42049e400, 0xc420456000)
	/Users/r/src/upspin.io/rpc/client.go:311 +0x442
created by upspin.io/rpc.(*httpClient).Invoke
	/Users/r/src/upspin.io/rpc/client.go:268 +0x5a9

goroutine 84 [IO wait]:
internal/poll.runtime_pollWait(0x1781d50, 0x72, 0x0)
	/Users/r/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200a0098, 0x72, 0xffffffffffffff00, 0x15e50e0, 0x15e14e0)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200a0098, 0xc4208b2000, 0x8000, 0x8000)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200a0080, 0xc4208b2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc4200a0080, 0xc4208b2000, 0x8000, 0x8000, 0x1, 0x4, 0xc420042788)
	/Users/r/go/src/net/fd_unix.go:204 +0x52
net.(*conn).Read(0xc4204b2008, 0xc4208b2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/r/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc420464390, 0x1b50000, 0xc4204b2008, 0x5, 0xc4204b2008, 0xc4207def60)
	/Users/r/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420410700, 0x1430b17, 0xc420410820, 0x102e17b)
	/Users/r/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420410700, 0xc4203e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/r/go/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc4200919e0, 0xc4203e6000, 0x1000, 0x1000, 0xc420015780, 0xc420022298, 0x10538e0)
	/Users/r/go/src/net/http/transport.go:1373 +0x140
bufio.(*Reader).fill(0xc42041c9c0)
	/Users/r/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc42041c9c0, 0x1, 0x0, 0x0, 0x0, 0xc4223c41e0, 0x0)
	/Users/r/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc4200919e0)
	/Users/r/go/src/net/http/transport.go:1521 +0x185
created by net/http.(*Transport).dialConn
	/Users/r/go/src/net/http/transport.go:1168 +0xa2e

goroutine 85 [select]:
net/http.(*persistConn).writeLoop(0xc4200919e0)
	/Users/r/go/src/net/http/transport.go:1751 +0x165
created by net/http.(*Transport).dialConn
	/Users/r/go/src/net/http/transport.go:1169 +0xa53

goroutine 69 [select, 45 minutes]:
net/http.(*persistConn).writeLoop(0xc4204b6000)
	/Users/r/go/src/net/http/transport.go:1751 +0x165
created by net/http.(*Transport).dialConn
	/Users/r/go/src/net/http/transport.go:1169 +0xa53

goroutine 114081 [IO wait]:
internal/poll.runtime_pollWait(0x1781ed0, 0x72, 0x0)
	/Users/r/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420198018, 0x72, 0xffffffffffffff00, 0x15e50e0, 0x15e14e0)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420198018, 0xc4204a3f00, 0x1, 0x1)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420198000, 0xc4204a3f91, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc420198000, 0xc4204a3f91, 0x1, 0x1, 0xc421a9d320, 0x0, 0x15e3001)
	/Users/r/go/src/net/fd_unix.go:204 +0x52
net.(*conn).Read(0xc420492038, 0xc4204a3f91, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/r/go/src/net/net.go:176 +0x6d
net/http.(*connReader).backgroundRead(0xc4204a3f80)
	/Users/r/go/src/net/http/server.go:656 +0x62
created by net/http.(*connReader).startBackgroundRead
	/Users/r/go/src/net/http/server.go:652 +0xd8

goroutine 114092 [IO wait]:
internal/poll.runtime_pollWait(0x1781e10, 0x72, 0x0)
	/Users/r/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4204ae118, 0x72, 0xffffffffffffff00, 0x15e50e0, 0x15e14e0)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4204ae118, 0xc4211e2000, 0x8000, 0x8000)
	/Users/r/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4204ae100, 0xc4211e2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/r/go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc4204ae100, 0xc4211e2000, 0x8000, 0x8000, 0x4e8, 0x8, 0x0)
	/Users/r/go/src/net/fd_unix.go:204 +0x52
net.(*conn).Read(0xc420492028, 0xc4211e2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/r/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc4204a2120, 0x1b50000, 0xc420492028, 0x5, 0xc420492028, 0x0)
	/Users/r/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420032e00, 0x1430b17, 0xc420032f20, 0x0)
	/Users/r/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420032e00, 0xc4203e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/r/go/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc4204b6000, 0xc4203e8000, 0x1000, 0x1000, 0xc4204a28f0, 0xc4203e8253, 0x2)
	/Users/r/go/src/net/http/transport.go:1373 +0x140
bufio.(*Reader).fill(0xc42040ea20)
	/Users/r/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc42040ea20, 0xc42040ea0a, 0xc4204a28f0, 0x2, 0x2, 0x2, 0x0)
	/Users/r/go/src/bufio/bufio.go:338 +0x2c
net/http/internal.readChunkLine(0xc42040ea20, 0x15e2b60, 0xc42040ea20, 0xc4204a28f0, 0x2, 0x2)
	/Users/r/go/src/net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc4204a28d0)
	/Users/r/go/src/net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc4204a28d0, 0xc42009ed0c, 0x4, 0x4, 0x102ae19, 0xc400000008, 0xc42049f540)
	/Users/r/go/src/net/http/internal/chunked.go:93 +0x13b
net/http.(*body).readLocked(0xc42049e3c0, 0xc42009ed0c, 0x4, 0x4, 0x102b7b6, 0x1430398, 0xc4201fd648)
	/Users/r/go/src/net/http/transfer.go:779 +0x67
net/http.(*body).Read(0xc42049e3c0, 0xc42009ed0c, 0x4, 0x4, 0x0, 0x0, 0x0)
	/Users/r/go/src/net/http/transfer.go:771 +0xea
net/http.(*bodyEOFSignal).Read(0xc42049e400, 0xc42009ed0c, 0x4, 0x4, 0x0, 0x0, 0x0)
	/Users/r/go/src/net/http/transport.go:2116 +0xe9
io.ReadAtLeast(0x15e3420, 0xc42049e400, 0xc42009ed0c, 0x4, 0x4, 0x4, 0xc421130840, 0x0, 0x15e3001)
	/Users/r/go/src/io/io.go:307 +0x86
io.ReadFull(0x15e3420, 0xc42049e400, 0xc42009ed0c, 0x4, 0x4, 0x15e3101, 0xc4206f5130, 0x1b100c8)
	/Users/r/go/src/io/io.go:325 +0x58
upspin.io/rpc.readFull.func1(0x15e3420, 0xc42049e400, 0xc42009ed0c, 0x4, 0x4, 0xc4215934a0)
	/Users/r/src/upspin.io/rpc/client.go:349 +0x5d
created by upspin.io/rpc.readFull
	/Users/r/src/upspin.io/rpc/client.go:345 +0xb0
% 
% which cacheserver
/Users/r/bin/cacheserver
% ls -l /Users/r/bin/cacheserver
-rwxr-xr-x  1 r  staff  9538284 Jul  5 08:51 /Users/r/bin/cacheserver
% 
```

**Comment by robpike** [comment]
Fixed
