### ISSUE TITLE
upspin: DirEntry.Unmarshal can panic if given bad data

### ISSUE THREAD

**Issue by adg** [upspin/upspin#425]
A recent failure on the continuous builder showed this panic in the DirEntry.Unmarshal method:

```
panic: runtime error: makeslice: len out of range

goroutine 285 [running]:
upspin.io/upspin.(*DirEntry).Unmarshal(0xc4230c1cf8, 0xc42115241a, 0xb3b, 0xb3b, 0xb55, 0xb55, 0x0, 0x0, 0x4159b0)
	/home/travis/gopath/src/upspin.io/upspin/code.go:249 +0xee6
upspin.io/dir/server/tree.(*LogEntry).unmarshal(0xc4230c1cf0, 0xc423272320, 0xc423272320, 0x309)
	/home/travis/gopath/src/upspin.io/dir/server/tree/log.go:884 +0xf96
upspin.io/dir/server/tree.(*Reader).ReadAt(0xc421f89540, 0x309, 0xffffffffffffffe4, 0xc423272340, 0x12, 0x0, 0x0, 0x1000, 0xffffffffffffffeb, 0x0, ...)
	/home/travis/gopath/src/upspin.io/dir/server/tree/log.go:414 +0x948
upspin.io/dir/server/tree.(*watcher).sendEventFromLog(0xc421f89740, 0x309, 0xc421f89740, 0x0, 0x0)
	/home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:284 +0x100
upspin.io/dir/server/tree.(*watcher).watch(0xc421f89740, 0x309)
	/home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:312 +0x8b
created by upspin.io/dir/server/tree.(*Tree).Watch
	/home/travis/gopath/src/upspin.io/dir/server/tree/watch.go:146 +0x892
```

The line in question is the one with `make` here:

```

        // Blocks. First a varint count, then the blocks.
        nBlocks, n := binary.Varint(b)
        if n == 0 {
                return nil, ErrTooShort
        }
        b = b[n:]
        d.Blocks = nil
        if nBlocks > 0 {
                d.Blocks = make([]DirBlock, nBlocks)
                for i := range d.Blocks {
                        var err error
                        b, err = d.Blocks[i].Unmarshal(b)
                        if err != nil {
                                return nil, err
                        }
                }
        }
```

Presumably we could be more defensive here.

As an aside, we should probably run [go-fuzz](https://github.com/dvyukov/go-fuzz) on all our marshaling/unmarshaling functions.

**Comment by edpin** [comment]
As pointed out in #347. There might be other places where this happens. Maybe this bug could catch all.
