### ISSUE TITLE
cmd/upspin: panic when dirserver returns nil, upspin.ErrFollowLink

### ISSUE THREAD

**Issue by stapelberg** [upspin/upspin#451]
I’ve been playing around with a custom DirServer. During development, I noticed that when I didn’t return an upspin.DirEntry, but just used `return nil, upspin.ErrFollowLink`, the upspin client would panic:

```
% upspin -log debug -config=~/upspin-dcs/config ls michael+dcs@stapelberg.ch/bleh/
2017/08/17 18:36:50.798664 dir/remote.Dial("unassigned")("michael+dcs@stapelberg.ch", "remote,localhost:20443")
2017/08/17 18:36:50.798887 dir/remote.Lookup("remote,localhost:20443")("michael+dcs@stapelberg.ch/bleh/")
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x62f30f]

goroutine 1 [running]:
upspin.io/client.(*Client).lookup(0xc420106710, 0x8f0d76, 0xd, 0xc42001c2d0, 0x90db20, 0xc42010ce01, 0xc420140070, 0x0, 0x0, 0x0, ...)
	/home/michael/go/src/upspin.io/client/client.go:551 +0x25f
upspin.io/client.(*Client).Lookup(0xc420106710, 0x7ffd7e6fb8b8, 0x1f, 0x1, 0x0, 0x0, 0x0)
	/home/michael/go/src/upspin.io/client/client.go:490 +0x120
upspin.io/subcmd.(*State).GlobUpspin(0xc420140000, 0x7ffd7e6fb8b8, 0x1f, 0xc420108090, 0x0, 0x1)
	/home/michael/go/src/upspin.io/subcmd/io.go:215 +0x278
upspin.io/subcmd.(*State).GlobAllUpspin(0xc420140000, 0xc420010110, 0x1, 0x1, 0xc420105650, 0x906870, 0xe9)
	/home/michael/go/src/upspin.io/subcmd/io.go:188 +0xbd
main.(*State).ls(0xc420106220, 0xc420010110, 0x1, 0x1)
	/home/michael/go/src/upspin.io/cmd/upspin/ls.go:40 +0x221
main.(*State).run(0xc420106220, 0xc420010100, 0x2, 0x2)
	/home/michael/go/src/upspin.io/cmd/upspin/main.go:162 +0x99
main.main()
	/home/michael/go/src/upspin.io/cmd/upspin/main.go:129 +0x177
```

Let me know if you need more details / steps to reproduce.

**Comment by robpike** [comment]
Thanks for the report. Should be easy to fix, and should be fixed.

However, I hope you understand that returning nil with a ErrFollowLink won't work, as ErrFollowLink requires a link to follow, which is provided by a non-nil DirEntry.

**Comment by stapelberg** [comment]
Yes, that’s understood, thanks.
