### ISSUE TITLE
cmd/upspinfs: crash due to unsynchronized map access

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#542]
upspinfs build from Nov 15 (commit hash: c8e3ca56) crashes like so:

```
fatal error: concurrent map read and map write

goroutine 484103 [running]:
runtime.throw(0x1481279, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4209a1890 sp=0xc4209a1870 pc=0x102bc85
runtime.mapaccess2_faststr(0x13f5560, 0xc42023c0c0, 0xc42d602000, 0x2a, 0xc42d7538e0, 0x1)
	/usr/local/go/src/runtime/hashmap_fast.go:324 +0x47a fp=0xc4209a18e8 sp=0xc4209a1890 pc=0x100db0a
main.(*node).openDir(0xc42bcbfe00, 0x1676c60, 0xc42cf3b880, 0xc42e3d2e80, 0xc4202011f0, 0x0, 0x0, 0x0, 0x0)
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:380 +0x820 fp=0xc4209a1a70 sp=0xc4209a18e8 pc=0x1386ad0
main.(*node).Open(0xc42bcbfe00, 0x1676c60, 0xc42cf3b880, 0xc42e3d2e80, 0xc4202011f0, 0x1, 0x0, 0x166ff60, 0xc420307740)
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:330 +0x5f fp=0xc4209a1ac8 sp=0xc4209a1a70 pc=0x13861ef
upspin.io/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc4200b80c0, 0x1676c60, 0xc42cf3b880, 0x166ffa0, 0xc42bcbfe00, 0xc4201d2840, 0x1675f20, 0xc42e3d2e80, 0xc4209a1ef8, 0xc42d1bede0, ...)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:1086 +0x18e3 fp=0xc4209a1e10 sp=0xc4209a1ac8 pc=0x1210263
upspin.io/vendor/bazil.org/fuse/fs.(*Server).serve(0xc4200b80c0, 0x1675f20, 0xc42e3d2e80)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:878 +0x468 fp=0xc4209a1fa0 sp=0xc4209a1e10 pc=0x120e528
upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200b80c0, 0x1675f20, 0xc42e3d2e80)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e fp=0xc4209a1fc8 sp=0xc4209a1fa0 pc=0x1212c5e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4209a1fd0 sp=0xc4209a1fc8 pc=0x1059701
created by upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:423 +0x35f

goroutine 1 [chan receive, 3408 minutes]:
main.main()
	/Users/m/src/upspin.io/cmd/upspinfs/main.go:87 +0x661

goroutine 5 [syscall, 3408 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [select, 3408 minutes, locked to thread]:
runtime.gopark(0x14914f8, 0x0, 0x1475962, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420038f50, 0xc420076120)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x1fe
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 7 [chan receive, 3408 minutes]:
upspin.io/shutdown.init.0.func1(0xc42005e4e0)
	/Users/m/src/upspin.io/shutdown/shutdown.go:73 +0x4b
created by upspin.io/shutdown.init.0
	/Users/m/src/upspin.io/shutdown/shutdown.go:72 +0xdf

goroutine 18 [chan receive]:
main.(*upspinFS).invalidateProc(0xc420236090)
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:643 +0x49
created by main.newUpspinFS
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:144 +0x3e0

goroutine 14 [syscall]:
syscall.Syscall(0x3, 0x6, 0xc42a524000, 0x1001000, 0x10616a0, 0x16c2550, 0xc420605500)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x6, 0xc42a524000, 0x1001000, 0x1001000, 0x10f060f, 0xc42024c010, 0x6)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:954 +0x55
syscall.Read(0x6, 0xc42a524000, 0x1001000, 0x1001000, 0x30, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
upspin.io/vendor/bazil.org/fuse.(*Conn).ReadRequest(0xc4200de180, 0x14917b8, 0xc4200b80c0, 0x1675ae0, 0xc42d856340)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fuse.go:552 +0xb1
upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve(0xc4200b80c0, 0x166ffe0, 0xc420236090, 0x0, 0x0)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:414 +0x373
main.do.func2(0xc420236090, 0xc4200de180, 0xc42026e0c0)
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:1086 +0x140
created by main.do
	/Users/m/src/upspin.io/cmd/upspinfs/fs.go:1084 +0x63c

goroutine 82 [IO wait, 3408 minutes]:
internal/poll.runtime_pollWait(0x1c24eb8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42009c018, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42009c018, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42009c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc42009c000, 0xc420039e78, 0x101333d, 0xc4202620e8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*UnixListener).accept(0xc420280000, 0x10e86f5, 0xc4202620e8, 0xc4200fa000)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc420280000, 0xc420014090, 0x13edea0, 0x16c0fe0, 0x14674a0)
	/usr/local/go/src/net/unixsock.go:241 +0x49
net/http.(*Server).Serve(0xc4200fa000, 0x1675120, 0xc420280000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
main.main.func1(0xc4200fa000, 0x1675120, 0xc420280000)
	/Users/m/src/upspin.io/cmd/upspinfs/main.go:83 +0x43
created by main.main
	/Users/m/src/upspin.io/cmd/upspinfs/main.go:82 +0x64a

goroutine 396221 [select]:
net/http.(*persistConn).writeLoop(0xc42d8c4000)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 396251 [IO wait]:
internal/poll.runtime_pollWait(0x1c247f8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42d412118, 0x72, 0xffffffffffffff00, 0x16721a0, 0x166e508)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42d412118, 0xc420798000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42d412100, 0xc420798000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42d412100, 0xc420798000, 0x1000, 0x1000, 0x102d94b, 0xc420d49a40, 0x1055800)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42d79c288, 0xc420798000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42d8c4240, 0xc420798000, 0x1000, 0x1000, 0xc42d310280, 0xc42d8f8478, 0x1053980)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc42080ed20)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc42080ed20, 0x1, 0x0, 0x0, 0x0, 0xc4201660c0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42d8c4240)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 481805 [runnable]:
upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200b80c0, 0x1675ae0, 0xc42d856340)
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:423
created by upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve
	/Users/m/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:423 +0x35f

goroutine 396220 [IO wait]:
internal/poll.runtime_pollWait(0x1cd10a8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42009c218, 0x72, 0xffffffffffffff00, 0x16721a0, 0x166e508)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42009c218, 0xc4201db000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42009c200, 0xc4201db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42009c200, 0xc4201db000, 0x1000, 0x1000, 0x102d94b, 0xc42003ba40, 0x1055800)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42d79c1e8, 0xc4201db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42d8c4000, 0xc4201db000, 0x1000, 0x1000, 0xc423452080, 0xc42d8f8358, 0x1053980)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4200ddda0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4200ddda0, 0x1, 0x0, 0x0, 0x0, 0xc4233221e0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42d8c4000)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 396252 [select]:
net/http.(*persistConn).writeLoop(0xc42d8c4240)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53
```

**Comment by presotto** [comment]
Thanks, I got sloppy with locking.  CL coming.
