### ISSUE TITLE
fuse: panic in handler for Open [ID=0x3188 Node=0x42 Uid=89956 Gid=5000 Pid=19621] dir=false fl=OpenWriteOnly: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by filmil** [upspin/upspin#621]
```
2019/04/19 07:01:49.841063 store/storecache.scheduler: writeback failed: store/remote("udir.filmar.us:443").Put: I/O error:
        rpc.Invoke: Post https://udir.filmar.us:443/api/Store/Put: dial tcp 76.102.115.147:443: connect: connection timed out
2019/04/19 00:02:05 fuse: panic in handler for Open [ID=0x3188 Node=0x42 Uid=89956 Gid=5000 Pid=19621] dir=false fl=OpenWriteOnly: runtime error: invalid memory address or nil pointer dereference
goroutine 12857 [running]:
upspin.io/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x8dce00, 0xc0003fb880, 0xc0000cfef8, 0xc0000cfe77)
        /home/fmil/work/go/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:857 +0x1ac
panic(0x7ebe00, 0xba1480)
        /home/fmil/local/opt/go/src/runtime/panic.go:513 +0x1b9
main.(*cache).open(0xc00015aff0, 0xc000297de0, 0x1, 0xc0002ae000, 0xb)
        /home/fmil/work/go/src/upspin.io/cmd/upspinfs/cache.go:180 +0x3df
main.(*node).openFile(0xc00027c6e0, 0x8de2c0, 0xc00023a180, 0xc0003fb880, 0xc0002c2b80, 0x0, 0x0, 0x0, 0x0)
        /home/fmil/work/go/src/upspin.io/cmd/upspinfs/fs.go:456 +0x251
main.(*node).Open(0xc00027c6e0, 0x8de2c0, 0xc00023a180, 0xc0003fb880, 0xc0002c2b80, 0x3236363846424301, 0x3637393933423641, 0x3338313346444630, 0xe8e40059c003039)
        /home/fmil/work/go/src/upspin.io/cmd/upspinfs/fs.go:372 +0xe4
upspin.io/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc000372000, 0x8de2c0, 0xc00023a180, 0x8d8aa0, 0xc00027c6e0, 0xc000151ec0, 0x8dce00, 0xc0003fb880, 0xc0000cfef8, 0x1473726574726f70, ...)
        /home/fmil/work/go/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:1086 +0x17e7
upspin.io/vendor/bazil.org/fuse/fs.(*Server).serve(0xc000372000, 0x8dce00, 0xc0003fb880)
        /home/fmil/work/go/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:878 +0x410
upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc000372000, 0x8dce00, 0xc0003fb880)
        /home/fmil/work/go/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by upspin.io/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/fmil/work/go/src/upspin.io/vendor/bazil.org/fuse/fs/serve.go:423 +0x31e
```

**Comment by adg** [comment]
cc @presotto

**Comment by presotto** [comment]
Looking.
